### ISSUE TITLE
ibm_installmgr resource creates required directories on /

### ISSUE THREAD

**Issue by dusty73** [Sainsburys/ibm-installmgr#17]
In "**ibm_installmgr**" resource you wrote the required directories in the form:
`dirs = %w(ibm_root_dir extract_dir install_dir data_location)`

The %w operator defines an array of strings, where the strings are the literals between the parenteses, it's as if you wrote:
`dirs = ["ibm_root_dir", "extract_dir", "install_dir", "data_location"]`
This leads to have the recipe to create in "/" directories named "ibm_root_dir", "extract_dir", etc.

I think you meant to do this:
`dirs = [ibm_root_dir, extract_dir, install_dir, data_location]`

**Comment by chrisminton** [comment]
This is resolved in `v1.3.0`
